### ISSUE TITLE
HIST_IGNORE_SPACE オプションに対応させてほしい

### ISSUE THREAD

**Issue by seroqn** [yuki-yano/zeno.zsh#55]
zsh の HIST_IGNORE_SPACE （スペースから始まるコマンドラインは履歴に残さない）を有効にして使っています。
しかしコマンドライン行頭に空白文字を入れた状態で snippet 展開すると行頭の空白が削除されてしまいます。
行頭空白を保存したまま展開させられるようにはできませんか？

**Comment by yuki-yano** [comment]
遅れましたが対応できたかと思います
プラグインの更新をお願いできるでしょうか

**Comment by seroqn** [comment]
ありがとうございます。助かります。
