### ISSUE TITLE
zsh-syntax-hightlighting と一緒に使うとエラーが出る

### ISSUE THREAD

**Issue by Warashi** [yuki-yano/zeno.zsh#57]
便利に使わせていただいています。開発ありがとうございます！
使っていてエラー出力が出ることがあったので、Issueをあげさせてもらいます。

zsh-syntax-hightlighting と一緒に使うとこのようなエラー出力が出ることがあります。
```
_zsh_highlight:17: bad set of key/value pairs for associative array
```

おそらくこちらのIssueと同じで [optionsという変数名がつかわれている](https://github.com/yuki-yano/zeno.zsh/blob/045d0b8eebad9202666a7da0d0a8093f4fbca418/shell/snippet/widget/zeno-completion#L19) ことが原因かなと思います。

> The cause is that zaw creates a variable named options, hiding clashing with the variable of the same name provided by zsh itself via a standard module.

https://github.com/zsh-users/zsh-syntax-highlighting/issues/500#issuecomment-360765678

**Comment by yuki-yano** [comment]
返信が遅れてしまいすみません。
他の方からも相性が悪いという話は聞いていたんですがそれが原因だったんですね。
https://github.com/zdharma-continuum/fast-syntax-highlighting の方が個人的には推奨なんですが、ひとまずこれで試して貰えるでしょうか？
READMEに併用を非推奨って書いておくとかやってもよさそうですね。

あまりに問題になりそうならコードレベルで対応を検討しようと思います。

**Comment by Warashi** [comment]
返信ありがとうございます。
たしかにそちらのプラグインでならエラー出ませんでした。ありがとうございます！
READMEに併用を非推奨で代替としてこのプラグインを書いておくのはよさそうですね。

**Comment by yuki-yano** [comment]
追記しておきました
https://github.com/yuki-yano/zeno.zsh/commit/f65a1ca643a4dc4f48536da48115e2a3895a5692
